### ISSUE TITLE
First test of issue system

### ISSUE THREAD

**Issue by FlynnTheMighty** [fundamental-technologies-llc/galileo-issues-repository#1]
[EpdQuestions - 20210625_072747.pdf](https://github.com/fundamental-technologies-llc/galileo-issues-repository/files/6716184/EpdQuestions.-.20210625_072747.pdf)

**Comment by LucasMiller** [comment]
@FlynnTheMighty --> All of the values that you flagged with the int/float ambiguity are being handled consistently internally as floats. When the routine that converts CDF's to CSV's operates it outputs values it truncates those that have a zero decimal portion: e.g. "40.0" is written out as "40". 

I would set your reading software to interpret any of the Energy and Energy_Range values as floats or doubles, depending on your preference.
