### ISSUE TITLE
pitch angle test

### ISSUE THREAD

**Issue by FlynnTheMighty** [fundamental-technologies-llc/galileo-issues-repository#2]
In this test I am looking at the first record in 'galileo_epd_level2_comprehensive_ver-1.1.1-01.csv'

I took the look direction and mag field and calculated the pitch angle and compared it to the pitch angle in the record.  It is my understanding they should be the same.
![image](https://user-images.githubusercontent.com/86371100/123427600-72040000-d58a-11eb-8785-587c64661d1d.png)

**Comment by LucasMiller** [comment]
The reason for this _particular_ issue is that I mistakenly included the Look Direction in IAU_JUPITER coordinates and the magnetic field in SC_COORDS. Whereas the pitch angle was calculated with both vectors expressed in the same coordinate system (as they should be). 

I am reprocessing the CDF's and outputting both the look and the magnetic field vector in IAU_JUPITER coords. They won't necessarily be _correct_; but the pitch angle should at least be the angle between these two vectors. 

I am currently processing 96309.rat to compare the resulting look vectors and magnetic field with @FlynnTheMighty  calculations.
