### ISSUE TITLE
Time stamp issues

### ISSUE THREAD

**Issue by FlynnTheMighty** [fundamental-technologies-llc/galileo-issues-repository#7]
I noticed when looking for bite out features in the particle data that the time between 64 records was around 10s and not 20s.  I am including the Ganymede
[Ganymede.pdf](https://github.com/fundamental-technologies-llc/galileo-issues-repository/files/7001632/Ganymede.pdf)
 moon encounters as an example.  I found the same issue in all the Europa and Callisto moon encounters.

**Comment by LucasMiller** [comment]
Looking at galileo_epd_level2_lunar_ganymede-ver-1.1.1-01.csv
Timestamp for first 64 sector record (FileSpinNumber=4, RecordType=1): 1996-250T18:33:33.451
Timestamp for last 64 sector record in that spin: 1996-250T18:33:52.156

DeltaT in this case is approximately the expected 20 second spin period. This pattern appears to continue... am I missing something?

**Comment by FlynnTheMighty** [comment]
I might be misunderstanding the structure of the CSV file.  Here is the first 64 times stamps from the Ganymede csv file.
[First64TimeStampsOfCSV.pdf](https://github.com/fundamental-technologies-llc/galileo-issues-repository/files/7001798/First64TimeStampsOfCSV.pdf)


I thought the first record (2) after the header and the 66th should be 20s apart.

**Comment by LucasMiller** [comment]
Ahhh... no, the RecordMode 64 (RecordType = 1), 32 (RecordType = 2), and 16 (RecordType = 3) sector records are all interleaved in this file.
 
If you want to work with the high resolution RecordMode records then sort the CSV file on the RecordType column and keep RecordType =1.  After that records that are a spin apart (approx 64 records if there was a full spin of data) will have timestamps that differ by about 20 seconds.
